### ISSUE TITLE
Looped events never end

### ISSUE THREAD

**Issue by dukeimg** [dukeimg/transistor-breach#1]
Some sound events (such background music) will never stop because they are looped. It's becoming a problem when you try to write them to file with `FMOD_OUTPUTTYPE_WAVWRITER` or `FMOD_OUTPUTTYPE_WAVWRITER_NRT`.

**Comment by lilsweetcaligula-devv** [comment]
Could you please elaborate on the nature of the problem? RecurseSounds appears to not be having a terminating condition and thus calls itself infinitely. Hmm...

**Comment by lilsweetcaligula** [comment]
Could you please elaborate on the nature of the problem? RecurseSounds appears to not be having a terminating condition and thus calls itself infinitely. Hmm...
